version: '2'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/usr/src/app/
    env_file: .env

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
