version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    env_file:
      - ./web/.env
    command: gunicorn -w 1 -b :8000 run:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    image: "redis:alpine"
